# Generated by Django 4.2.5 on 2023-10-04 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "ordering": ["nome"],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterModelOptions(
            name="evento",
            options={"verbose_name": "Evento", "verbose_name_plural": "Eventos"},
        ),
    ]
