# Generated by Django 4.2.5 on 2023-10-16 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0003_remove_evento_publicado_evento_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inscricaoevento",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Inscrição em Evento",
                "verbose_name_plural": "Inscrições em Eventos",
            },
        ),
        migrations.AddField(
            model_name="inscricaoevento",
            name="modificado_em",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Modificado em"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eventos",
                to="eventos.categoria",
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterModelTable(
            name="inscricaoevento",
            table="inscricao_evento",
        ),
    ]
