# Generated by Django 4.2.5 on 2023-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "preferencia_evento",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Preferencia Eventos"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
            ],
        ),
    ]
